version: '3.8'

services:
  fastapi_tool_server:
    container_name: fastapi_tool_server
    build:
      context: ../..
      dockerfile: app/docker/Dockerfile.prod
    ports:
      - "5002:8000"  # Using port 5002 to avoid conflicts with Dify.ai services
    environment:
      - DATABASE_URI=postgresql://ai_tool_user:${DB_PASSWORD}@fastapi_tool_db:5432/ai_tool_db
      - FASTAPI_API_KEY=${FASTAPI_API_KEY}
      - LOG_LEVEL=INFO
    networks:
      - fastapi_tool_network
      - dify_network  # To allow communication with Dify services if needed
    depends_on:
      fastapi_tool_db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  fastapi_tool_db:
    container_name: fastapi_tool_db
    image: postgres:15-alpine
    ports:
      - "5435:5432"  # Changed from 5434 to avoid potential conflicts
    environment:
      - POSTGRES_USER=ai_tool_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ai_tool_db
    volumes:
      - fastapi_tool_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fastapi_tool_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_tool_user -d ai_tool_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  fastapi_tool_network:
    name: fastapi_tool_network
    driver: bridge
  dify_network:
    external: true
    name: dify_network  # This should match Dify's network name

volumes:
  fastapi_tool_postgres_data:
    name: fastapi_tool_postgres_data_prod  # Different name for production 
